name: ci

on:
  workflow_dispatch:
  push:
    branches:
      - 'main'
  pull_request: {}

concurrency:
  group: '${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}'
  cancel-in-progress: true

jobs:
  # test:
  #   timeout-minutes: 5
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: 📖 Check out repo
  #       uses: actions/checkout@v3
  #     - name: ⚙️ Set up Node
  #       uses: actions/setup-node@v3
  #     - name: 🔎 Install dependencies
  #       run: npm i --force # todo: this should be npm ci
  #     - name: 👀 Lint
  #       run: npm run lint
  #     - name: 🧪 Test
  #       run: npm run test:coverage

  release:
    timeout-minutes: 5
    runs-on: ubuntu-latest
    # needs: test
    if: github.ref == 'refs/heads/main'
    steps:
      - name: 📖 Check out repo
        uses: actions/checkout@v3
      - name: ⚙️ Set up Node
        uses: actions/setup-node@v3
      - name: 🔎 Install dependencies
        run: npm i --force # todo: this should be npm ci
      - name: ⚒️ Build
        run: npm run build
      - name: 🚀 Release
        uses: cycjimmy/semantic-release-action@v3
        with:
          semantic_version: 16
          branches: |
            [
              'main'
            ]
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}